### ISSUE TITLE
确认这个界面，自己能看过去？

### ISSUE THREAD

**Issue by spritecn** [andytt/ErtuilEditor#3]

**Comment by ertuil** [comment]
早期项目 以学习 electron 为目的，所以可以做好但是没有必要（为什么不直接使用 vscode呢?)。此外这个仓库只是归档，停止维护。 还有建议你阅读以下 issues 礼仪中的下面一段话：

Avoid entitlement. The maintainers of the project don’t owe you anything. When you start using the project, it becomes your responsibility to help maintain it. If you don’t like the way the project is being maintained, be respectful when you provide suggestions and offer help to improve the situation. You can always fork the project to work on on your own if you feel very strongly it's not the direction you would personally take it.
